CREATE DATABASE IF NOT EXISTS auctionworld;
USE auctionworld;

CREATE TABLE IF NOT EXISTS users (
  discord_id BIGINT UNSIGNED PRIMARY KEY,
  jennies BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  discord_id BIGINT UNSIGNED NOT NULL,
  amount BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_transactions_discord_id (discord_id),
  UNIQUE KEY uq_transactions_discord_reason (discord_id, reason),
  CONSTRAINT fk_transactions_user
    FOREIGN KEY (discord_id) REFERENCES users(discord_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(255) PRIMARY KEY,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  discord_id BIGINT UNSIGNED NOT NULL,
  action ENUM('time_in', 'time_out') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_attendance_discord_id_created_at (discord_id, created_at)
);

CREATE TABLE IF NOT EXISTS admin_ranks (
  discord_id BIGINT UNSIGNED PRIMARY KEY,
  rank_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
